export const NOTHING_HAPPENED = 'NOTHING_HAPPENED';

export const REQUEST_LIST_START = 'REQUEST_LIST_START';
export const REQUEST_LIST_SUCCESS = 'REQUEST_LIST_SUCCESS';
export const REQUEST_LIST_FAILURE = 'REQUEST_LIST_FAILURE';

export const REQUEST_VIDEO_START = 'REQUEST_VIDEO_START';
export const REQUEST_VIDEO_SUCCESS = 'REQUEST_VIDEO_SUCCESS';
export const REQUEST_VIDEO_FAILURE = 'REQUEST_VIDEO_FAILURE';

export const UPLOAD_VIDEO_START = 'UPLOAD_VIDEO_START';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_FAILURE = 'UPLOAD_VIDEO_FAILURE';
export const UPLOAD_VIDEO_PROGRESS = 'UPLOAD_VIDEO_PROGRESS';

export const REQUEST_STATUS_SUCCESS = 'REQUEST_STATUS_SUCCESS';
export const REQUEST_STATUS_FAILURE = 'REQUEST_STATUS_FAILURE';

export const SWITCH_VIEW = 'SWITCH_VIEW';
export const GO_TO_LIST = 'GO_TO_LIST';
export const HIDE_ERRORS = 'HIDE_ERRORS';