export const REQUEST_LIST_START = 'REQUEST_LIST_START';
export const REQUEST_LIST_SUCCESS = 'REQUEST_LIST_SUCCESS';
export const REQUEST_LIST_FAILURE = 'REQUEST_LIST_FAILURE';

export const REQUEST_VIDEO_START = 'REQUEST_VIDEO_START';
export const REQUEST_VIDEO_SUCCESS = 'REQUEST_VIDEO_SUCCESS';
export const REQUEST_VIDEO_FAILURE = 'REQUEST_VIDEO_FAILURE';

export const SWITCH_VIEW = 'SWITCH_VIEW';
export const GO_TO_LIST = 'GO_TO_LIST';
export const HIDE_ERRORS = 'HIDE_ERRORS';